/* ============================================================
   langs.js — 51개 언어 데이터 (단일 소스)
   각 언어:
     id        : URL 파라미터 (?lang=ko)
     native    : 그 언어 표기 (선택 카드 큰 글씨)
     label     : 영어 표기 (카드 작은 글씨)
     ready     : true → 선택화면 노출 / false → 숨김
     dir       : "rtl" (아랍/히브리/페르시아/이디시) | 없으면 ltr
     title     : 히어로 카피 1행
     sub       : 히어로 카피 2행
     proof     : 앱 마퀴 아래 한 줄
     cap1      : 책 목업1 캡션
     cap2      : 책 목업2 캡션
     ytLabel   : 유튜브 아래 한 줄
     buyLabel  : 풍선 / 구매 단어
     back      : buy 페이지 "돌아가기"
     soon      : "준비 중" (버튼/페이지 공용)
     soonSub   : 준비중 페이지 보조문구
     stores    : [{name, fmt:["ebook"|"paper"|"hard"], url}]  (url "" → 준비중 버튼)
   ─ 규칙 ─
     · stores 가 비었거나 url 이 전부 비면 buy 페이지는 "준비 중"
     · url 한 줄 채우고 ready:true 로 바꾸면 그 언어가 사이트에 자동 등장
   ============================================================ */
const LANGS = [

{ id:"en", native:"English", label:"English", ready:true,
  title:"49 apps. One person.",
  sub:"One app a year is hard enough — I run 49.",
  proof:"They're all live on the App Store. Tap to see.",
  cap1:"From idea to launch —\nthe whole path.",
  cap2:"Not a book you read.\nA book you follow.",
  ytLabel:"Watch how it's made",
  buyLabel:"Buy", back:"Back",
  soon:"Coming soon", soonSub:"Available shortly.",
  stores:[
    {name:"Amazon US",   fmt:["ebook"], url:"https://www.amazon.com/dp/B0H246ZGKD"},
    {name:"Amazon UK",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"Kobo",        fmt:["ebook"], url:""},
  ]},

{ id:"zh-hans", native:"简体中文", label:"Chinese (Simplified)", ready:true,
  title:"一个人，49 个 App。",
  sub:"一年做一个都不容易 — 我运营着 49 个。",
  proof:"全部都在 App Store。点击查看。",
  cap1:"从选题到上架，\n全程在内。",
  cap2:"不是用来读的书，\n是用来跟着做的书。",
  ytLabel:"看制作过程",
  buyLabel:"购买", back:"返回",
  soon:"即将推出", soonSub:"即将上线。",
  stores:[
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"hi", native:"हिन्दी", label:"Hindi", ready:true,
  title:"अकेले, 49 ऐप्स।",
  sub:"साल में एक ऐप भी मुश्किल है — मैं 49 चलाता हूँ।",
  proof:"सभी App Store पर हैं। देखने के लिए टैप करें।",
  cap1:"विषय चुनने से लॉन्च तक —\nपूरा रास्ता।",
  cap2:"पढ़ने की किताब नहीं।\nकरने की किताब।",
  ytLabel:"बनने की प्रक्रिया देखें",
  buyLabel:"खरीदें", back:"वापस",
  soon:"जल्द आ रहा है", soonSub:"जल्द उपलब्ध।",
  stores:[
    {name:"Amazon.in",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"es", native:"Español", label:"Spanish", ready:true,
  title:"49 apps. Una persona.",
  sub:"Una app al año ya cuesta — yo gestiono 49.",
  proof:"Todas están en la App Store. Toca para verlas.",
  cap1:"De la idea al lanzamiento,\ntodo el camino.",
  cap2:"No es un libro que se lee.\nEs uno que se sigue.",
  ytLabel:"Mira cómo se hace",
  buyLabel:"Comprar", back:"Volver",
  soon:"Próximamente", soonSub:"Disponible muy pronto.",
  stores:[
    {name:"Amazon.es",     fmt:["ebook","paper"], url:""},
    {name:"Amazon.com.mx", fmt:["ebook","paper"], url:""},
    {name:"Apple Books",   fmt:["ebook"], url:""},
    {name:"Google Play",   fmt:["ebook"], url:""},
  ]},

{ id:"ar", native:"العربية", label:"Arabic", ready:true, dir:"rtl",
  title:"49 تطبيقًا. شخص واحد.",
  sub:"تطبيق واحد سنويًا صعب بما يكفي — أنا أدير 49.",
  proof:"كلها على App Store. انقر للاطلاع.",
  cap1:"من الفكرة إلى الإطلاق —\nالطريق كاملًا.",
  cap2:"ليس كتابًا تقرأه.\nبل كتاب تتبعه.",
  ytLabel:"شاهد كيف صُنع",
  buyLabel:"شراء", back:"رجوع",
  soon:"قريبًا", soonSub:"متاح قريبًا.",
  stores:[
    {name:"Amazon.ae",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"fr", native:"Français", label:"French", ready:true,
  title:"49 apps. Une personne.",
  sub:"Une app par an, c'est déjà dur — j'en gère 49.",
  proof:"Toutes sont sur l'App Store. Touchez pour voir.",
  cap1:"De l'idée au lancement,\ntout le parcours.",
  cap2:"Pas un livre qu'on lit.\nUn livre qu'on suit.",
  ytLabel:"Voir comment c'est fait",
  buyLabel:"Acheter", back:"Retour",
  soon:"Bientôt disponible", soonSub:"Disponible très bientôt.",
  stores:[
    {name:"Amazon.fr",   fmt:["ebook","paper"], url:""},
    {name:"Amazon.ca",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"Kobo",        fmt:["ebook"], url:""},
  ]},

{ id:"pt", native:"Português", label:"Portuguese", ready:true,
  title:"49 apps. Uma pessoa.",
  sub:"Um app por ano já é difícil — eu mantenho 49.",
  proof:"Estão todos na App Store. Toque para ver.",
  cap1:"Da ideia ao lançamento,\ntodo o caminho.",
  cap2:"Não é um livro pra ler.\nÉ um pra seguir.",
  ytLabel:"Veja como é feito",
  buyLabel:"Comprar", back:"Voltar",
  soon:"Em breve", soonSub:"Disponível em breve.",
  stores:[
    {name:"Amazon.com.br", fmt:["ebook","paper"], url:""},
    {name:"Amazon.pt",     fmt:["ebook"], url:""},
    {name:"Apple Books",   fmt:["ebook"], url:""},
    {name:"Google Play",   fmt:["ebook"], url:""},
  ]},

{ id:"ru", native:"Русский", label:"Russian", ready:true,
  title:"49 приложений. Один человек.",
  sub:"Одно приложение в год — уже много. У меня их 49.",
  proof:"Все они в App Store. Нажмите, чтобы посмотреть.",
  cap1:"От идеи до запуска —\nвесь путь.",
  cap2:"Не книга для чтения.\nКнига, которой следуют.",
  ytLabel:"Смотрите, как это сделано",
  buyLabel:"Купить", back:"Назад",
  soon:"Скоро", soonSub:"Скоро будет доступно.",
  stores:[
    {name:"ЛитРес",      fmt:["ebook"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"de", native:"Deutsch", label:"German", ready:true,
  title:"49 Apps. Eine Person.",
  sub:"Eine App pro Jahr ist schwer genug — ich betreibe 49.",
  proof:"Alle sind im App Store. Zum Ansehen tippen.",
  cap1:"Von der Idee bis zum Launch —\nder ganze Weg.",
  cap2:"Kein Buch zum Lesen.\nEins zum Nachmachen.",
  ytLabel:"Ansehen, wie es gemacht wird",
  buyLabel:"Kaufen", back:"Zurück",
  soon:"Demnächst", soonSub:"In Kürze verfügbar.",
  stores:[
    {name:"Amazon.de",   fmt:["ebook","paper"], url:""},
    {name:"Tolino",      fmt:["ebook"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"ja", native:"日本語", label:"Japanese", ready:true,
  title:"ひとりで、アプリ49個。",
  sub:"年に1個でも大変なのに — 私は49個を運営しています。",
  proof:"すべて App Store にあります。タップで確認。",
  cap1:"テーマ選びから公開まで、\nすべて。",
  cap2:"読む本ではなく、\nなぞる本。",
  ytLabel:"作る過程を動画で",
  buyLabel:"購入", back:"戻る",
  soon:"近日公開", soonSub:"まもなく公開します。",
  stores:[
    {name:"Amazon.co.jp", fmt:["ebook","paper"], url:""},
    {name:"楽天Kobo",     fmt:["ebook"], url:""},
    {name:"Apple Books",  fmt:["ebook"], url:""},
  ]},

{ id:"af", native:"Afrikaans", label:"Afrikaans", ready:true,
  title:"Op my eie, 49 apps.", sub:"Een app per jaar is al moeilik — ek bestuur 49.",
  proof:"Hulle is almal op die App Store.", cap1:"Van idee\ntot bekendstelling.",
  cap2:"Nie 'n boek om te lees nie.\nEen om te volg.", ytLabel:"Kyk hoe dit gemaak word",
  buyLabel:"Koop", back:"Terug", soon:"Binnekort", soonSub:"Binnekort beskikbaar.",
  stores:[ {name:"Amazon", fmt:["ebook"], url:""} ] },

{ id:"gsw", native:"Elsässisch", label:"Alsatian", ready:true,
  title:"Ganz elei, 49 Apps.", sub:"Ei App im Johr isch schun schwer — ich ha 49.",
  proof:"Sie sin alli im App Store.", cap1:"Vu de Idee\nbis zum Start.",
  cap2:"Kei Buech zum Läse.\nEis zum Nochmache.", ytLabel:"Lueg wie's gmacht wird",
  buyLabel:"Kaufe", back:"Zruck", soon:"Bald", soonSub:"Bald verfiegbar.",
  stores:[ {name:"Amazon.de", fmt:["ebook"], url:""} ] },

{ id:"eu", native:"Euskara", label:"Basque", ready:true,
  title:"Bakarrik, 49 app.", sub:"Urtean app bat ere zaila da — nik 49 kudeatzen ditut.",
  proof:"Denak App Store-n daude.", cap1:"Ideiatik kaleratzera —\nbide osoa.",
  cap2:"Ez irakurtzeko liburua.\nJarraitzekoa.", ytLabel:"Ikusi nola egiten den",
  buyLabel:"Erosi", back:"Atzera", soon:"Laster", soonSub:"Laster eskuragarri.",
  stores:[ {name:"Amazon.es", fmt:["ebook"], url:""} ] },

{ id:"br", native:"Brezhoneg", label:"Breton", ready:true,
  title:"Va-unan, 49 arload.", sub:"Un arload bep bloaz a zo diaes a-walc'h — 49 a veran.",
  proof:"Emaint holl war an App Store.", cap1:"Eus ar mennozh\nd'al lañsadur.",
  cap2:"Ket ul levr da lenn.\nUnan da heuliañ.", ytLabel:"Sellit penaos eo graet",
  buyLabel:"Prenañ", back:"Distreiñ", soon:"Da zont", soonSub:"Hegerz a-raok pell.",
  stores:[ {name:"Amazon.fr", fmt:["ebook"], url:""} ] },

{ id:"ca", native:"Català", label:"Catalan", ready:true,
  title:"Tot sol, 49 apps.", sub:"Una app a l'any ja costa — jo en gestiono 49.",
  proof:"Totes són a l'App Store.", cap1:"De la idea al llançament —\ntot el camí.",
  cap2:"No un llibre per llegir.\nUn per seguir.", ytLabel:"Mira com es fa",
  buyLabel:"Comprar", back:"Enrere", soon:"Aviat", soonSub:"Disponible aviat.",
  stores:[ {name:"Amazon.es", fmt:["ebook","paper"], url:""}, {name:"Apple Books", fmt:["ebook"], url:""} ] },

{ id:"zh-hant", native:"繁體中文", label:"Chinese (Traditional)", ready:true,
  title:"一個人，49 個 App。",
  sub:"一年做一個都不容易 — 我營運著 49 個。",
  proof:"全部都在 App Store。點擊查看。",
  cap1:"從選題到上架，\n全程在內。",
  cap2:"不是用來讀的書，\n是用來跟著做的書。",
  ytLabel:"看製作過程",
  buyLabel:"購買", back:"返回",
  soon:"即將推出", soonSub:"即將上線。",
  stores:[
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"Readmoo",     fmt:["ebook"], url:""},
  ]},

{ id:"kw", native:"Kernewek", label:"Cornish", ready:true,
  title:"My honan, 49 app.", sub:"Yth yw onan app y'n vlydhen kales lowr — my a worr 49.",
  proof:"Ymons i oll war an App Store.", cap1:"A dybyans\ndhe dhyllans.",
  cap2:"Nyns yw lyver dhe redya.\nOnan dhe sewya.", ytLabel:"Mir fatell yw gwrys",
  buyLabel:"Prena", back:"Dhe-dryw", soon:"Ow tos", soonSub:"Kavadow yn skon.",
  stores:[ {name:"Amazon.co.uk", fmt:["ebook"], url:""} ] },

{ id:"co", native:"Corsu", label:"Corsican", ready:true,
  title:"Solu, 49 app.", sub:"Una app à l'annu hè dighjà difficiule — ne gestiscu 49.",
  proof:"Sò tutte nant'à l'App Store.", cap1:"Da l'idea à u lanciu —\ntutta a strada.",
  cap2:"Micca un libru da leghje.\nUnu da seguità.", ytLabel:"Fighjate cumu hè fattu",
  buyLabel:"Cumprà", back:"Indietru", soon:"Prestu", soonSub:"Dispunibule prestu.",
  stores:[ {name:"Amazon.fr", fmt:["ebook"], url:""} ] },

{ id:"da", native:"Dansk", label:"Danish", ready:true,
  title:"49 apps. Én person.",
  sub:"Én app om året er svært nok — jeg driver 49.",
  proof:"De er alle på App Store. Tryk for at se.",
  cap1:"Fra idé til lancering —\nhele vejen.",
  cap2:"Ikke en bog at læse.\nEn at følge.",
  ytLabel:"Se hvordan den laves",
  buyLabel:"Køb", back:"Tilbage",
  soon:"Kommer snart", soonSub:"Snart tilgængelig.",
  stores:[
    {name:"Amazon",      fmt:["ebook"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Saxo",        fmt:["ebook"], url:""},
  ]},

{ id:"nl", native:"Nederlands", label:"Dutch", ready:true,
  title:"49 apps. Eén persoon.",
  sub:"Eén app per jaar is al zwaar — ik run er 49.",
  proof:"Ze staan allemaal in de App Store. Tik om te zien.",
  cap1:"Van idee tot lancering —\nde hele weg.",
  cap2:"Geen boek om te lezen.\nEén om te volgen.",
  ytLabel:"Bekijk hoe het gemaakt wordt",
  buyLabel:"Kopen", back:"Terug",
  soon:"Binnenkort", soonSub:"Binnenkort beschikbaar.",
  stores:[
    {name:"Amazon.nl",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"Kobo",        fmt:["ebook"], url:""},
  ]},

{ id:"frr-e", native:"Oostfreesk", label:"Eastern Frisian", ready:true,
  title:"Alleen, 49 Apps.", sub:"Een App in't Jahr is al swaar — ik hebb 49.",
  proof:"Se sünd all in'n App Store.", cap1:"Vun de Idee\nbit to'n Start.",
  cap2:"Keen Book to'n Lesen.\nEen to'n Namaken.", ytLabel:"Kiek, wo dat maakt warrt",
  buyLabel:"Kööp", back:"Torüch", soon:"Komt bald", soonSub:"Bald to kriegen.",
  stores:[ {name:"Amazon.de", fmt:["ebook"], url:""} ] },

{ id:"fi", native:"Suomi", label:"Finnish", ready:true,
  title:"49 sovellusta. Yksi henkilö.",
  sub:"Yksi sovellus vuodessa on jo vaikeaa — minulla on 49.",
  proof:"Kaikki ovat App Storessa. Katso napauttamalla.",
  cap1:"Ideasta julkaisuun —\nkoko matka.",
  cap2:"Ei luettava kirja.\nSeurattava kirja.",
  ytLabel:"Katso miten se tehdään",
  buyLabel:"Osta", back:"Takaisin",
  soon:"Tulossa pian", soonSub:"Pian saatavilla.",
  stores:[
    {name:"Amazon",      fmt:["ebook"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"fy", native:"Frysk", label:"Frisian", ready:true,
  title:"Yn myn ientsje, 49 apps.", sub:"Ien app yn 't jier is al dreech — ik rin der 49.",
  proof:"Se steane allegear op de App Store.", cap1:"Fan idee\noant lansearring.",
  cap2:"Gjin boek om te lêzen.\nIen om te folgjen.", ytLabel:"Sjoch hoe't it makke wurdt",
  buyLabel:"Keapje", back:"Werom", soon:"Komt gau", soonSub:"Gau beskikber.",
  stores:[ {name:"Amazon.nl", fmt:["ebook"], url:""} ] },

{ id:"gl", native:"Galego", label:"Galician", ready:true,
  title:"Só, 49 apps.", sub:"Unha app ao ano xa custa — eu xestiono 49.",
  proof:"Todas están na App Store.", cap1:"Da idea ao lanzamento —\ntodo o camiño.",
  cap2:"Non un libro para ler.\nUn para seguir.", ytLabel:"Mira como se fai",
  buyLabel:"Mercar", back:"Atrás", soon:"Proximamente", soonSub:"Dispoñible en breve.",
  stores:[ {name:"Amazon.es", fmt:["ebook"], url:""} ] },

{ id:"gu", native:"ગુજરાતી", label:"Gujarati", ready:true,
  title:"એકલા હાથે, 49 એપ્સ.", sub:"વર્ષે એક પણ અઘરી — હું 49 ચલાવું છું.",
  proof:"બધી App Store પર છે.", cap1:"વિચારથી\nલોન્ચ સુધી.",
  cap2:"વાંચવાનું નહીં,\nઅનુસરવાનું પુસ્તક.", ytLabel:"કેવી રીતે બને છે જુઓ",
  buyLabel:"ખરીદો", back:"પાછળ", soon:"ટૂંક સમયમાં", soonSub:"ટૂંક સમયમાં ઉપલબ્ધ.",
  stores:[ {name:"Amazon Kindle", fmt:["ebook"], url:""} ] },   /* eBook only */

{ id:"he", native:"עברית", label:"Hebrew", ready:true, dir:"rtl",
  title:"49 אפליקציות. אדם אחד.",
  sub:"אפליקציה אחת בשנה זה כבר קשה — אני מנהל 49.",
  proof:"כולן ב-App Store. הקש כדי לראות.",
  cap1:"מהרעיון להשקה —\nכל הדרך.",
  cap2:"לא ספר שקוראים.\nספר שעוקבים אחריו.",
  ytLabel:"צפו איך זה נעשה",
  buyLabel:"קנייה", back:"חזרה",
  soon:"בקרוב", soonSub:"זמין בקרוב.",
  stores:[
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"e-vrit",      fmt:["ebook"], url:""},
  ]},

{ id:"is", native:"Íslenska", label:"Icelandic", ready:true,
  title:"Einn, 49 öpp.", sub:"Eitt app á ári er nógu erfitt — ég rek 49.",
  proof:"Þau eru öll í App Store.", cap1:"Frá hugmynd að útgáfu —\nalla leiðina.",
  cap2:"Ekki bók til að lesa.\nBók til að fylgja.", ytLabel:"Sjáðu hvernig það er gert",
  buyLabel:"Kaupa", back:"Til baka", soon:"Væntanlegt", soonSub:"Fáanlegt fljótlega.",
  stores:[ {name:"Apple Books", fmt:["ebook"], url:""} ] },

{ id:"ga", native:"Gaeilge", label:"Irish", ready:true,
  title:"Liom féin, 49 aip.", sub:"Tá aon aip sa bhliain dian go leor — ritheann mé 49.",
  proof:"Tá siad uile ar an App Store.", cap1:"Ó smaoineamh go seoladh —\nan bealach ar fad.",
  cap2:"Ní leabhar le léamh.\nCeann le leanúint.", ytLabel:"Féach conas a dhéantar é",
  buyLabel:"Ceannaigh", back:"Ar ais", soon:"Ag teacht go luath", soonSub:"Ar fáil go luath.",
  stores:[ {name:"Amazon.co.uk", fmt:["ebook"], url:""} ] },

{ id:"it", native:"Italiano", label:"Italian", ready:true,
  title:"49 app. Una persona.",
  sub:"Un'app all'anno è già dura — io ne gestisco 49.",
  proof:"Sono tutte sull'App Store. Tocca per vederle.",
  cap1:"Dall'idea al lancio,\ntutto il percorso.",
  cap2:"Non un libro da leggere.\nUno da seguire.",
  ytLabel:"Guarda come si fa",
  buyLabel:"Acquista", back:"Indietro",
  soon:"Prossimamente", soonSub:"Presto disponibile.",
  stores:[
    {name:"Amazon.it",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"Kobo",        fmt:["ebook"], url:""},
  ]},

{ id:"ko", native:"한국어", label:"Korean", ready:true,
  title:"혼자서, 앱 49개.",
  sub:"1년에 1개도 벅찬데 — 저는 49개 운영합니다.",
  proof:"전부 App Store에 있습니다. 눌러서 확인하세요.",
  cap1:"주제 선정부터\n출시까지, 빠짐없이.",
  cap2:"읽는 책이 아니라,\n따라 하는 책.",
  ytLabel:"만드는 과정, 영상으로",
  buyLabel:"구매하기", back:"돌아가기",
  soon:"준비 중", soonSub:"곧 만나보실 수 있어요.",
  stores:[
    {name:"교보문고", fmt:["ebook"], url:""},
    {name:"알라딘",   fmt:["ebook","paper"], url:""},
    {name:"예스24",   fmt:["ebook"], url:""},
    {name:"리디",     fmt:["ebook"], url:""},
  ]},

{ id:"la", native:"Latina", label:"Latin", ready:true,
  title:"Solus, 49 applicationes.", sub:"Una per annum difficilis est — ego 49 administro.",
  proof:"Omnes in App Store sunt.", cap1:"Ab idea ad emissionem —\ntota via.",
  cap2:"Non liber legendus.\nLiber sequendus.", ytLabel:"Vide quomodo fiat",
  buyLabel:"Emere", back:"Retro", soon:"Mox", soonSub:"Mox disponibile.",
  stores:[ {name:"Amazon", fmt:["ebook"], url:""} ] },

{ id:"lb", native:"Lëtzebuergesch", label:"Luxembourgish", ready:true,
  title:"Eleng, 49 Apps.", sub:"Eng App d'Joer ass scho schwéier — ech bedreiwen der 49.",
  proof:"Si sinn all am App Store.", cap1:"Vun der Iddi\nbis zum Start.",
  cap2:"Kee Buch fir ze liesen.\nEe fir nozemaachen.", ytLabel:"Kuck wéi et gemaach gëtt",
  buyLabel:"Kafen", back:"Zréck", soon:"Geschwënn", soonSub:"Geschwënn verfügbar.",
  stores:[ {name:"Amazon.de", fmt:["ebook"], url:""} ] },

{ id:"ml", native:"മലയാളം", label:"Malayalam", ready:true,
  title:"ഒറ്റയ്ക്ക്, 49 ആപ്പുകൾ.", sub:"വർഷത്തിൽ ഒന്ന് പോലും പ്രയാസം — ഞാൻ 49 നടത്തുന്നു.",
  proof:"എല്ലാം App Store-ൽ ഉണ്ട്.", cap1:"ആശയം മുതൽ\nപ്രകാശനം വരെ.",
  cap2:"വായിക്കാനല്ല,\nപിന്തുടരാനുള്ള പുസ്തകം.", ytLabel:"എങ്ങനെ ഉണ്ടാക്കുന്നു എന്ന് കാണുക",
  buyLabel:"വാങ്ങുക", back:"പിന്നോട്ട്", soon:"ഉടൻ", soonSub:"ഉടൻ ലഭ്യമാകും.",
  stores:[ {name:"Amazon Kindle", fmt:["ebook"], url:""} ] },   /* eBook only */

{ id:"gv", native:"Gaelg", label:"Manx", ready:true,
  title:"My lomarcan, 49 app.", sub:"Ta un app sy vlein doillee dy liooar — ta mee jannoo 49.",
  proof:"T'ad ooilley er yn App Store.", cap1:"Veih smooinaghtyn\ngys cur magh.",
  cap2:"Cha nee lioar dy lhaih.\nFer dy eiyrt.", ytLabel:"Jeeagh kys t'eh jeant",
  buyLabel:"Kionnee", back:"Erash", soon:"Cheet dy gerrid", soonSub:"Ry-gheddyn dy gerrid.",
  stores:[ {name:"Amazon.co.uk", fmt:["ebook"], url:""} ] },

{ id:"mr", native:"मराठी", label:"Marathi", ready:true,
  title:"एकट्याने, 49 अ‍ॅप्स.", sub:"वर्षाला एकही कठीण — मी 49 चालवतो.",
  proof:"सर्व App Store वर आहेत.", cap1:"कल्पनेपासून\nप्रकाशनापर्यंत.",
  cap2:"वाचण्याचे नव्हे,\nअनुसरण्याचे पुस्तक.", ytLabel:"कसे बनते ते पाहा",
  buyLabel:"खरेदी", back:"मागे", soon:"लवकरच", soonSub:"लवकरच उपलब्ध.",
  stores:[ {name:"Amazon Kindle", fmt:["ebook"], url:""} ] },   /* eBook only */

{ id:"frr-n", native:"Nordfriisk", label:"Northern Frisian", ready:true,
  title:"Aliining, 49 Apps.", sub:"Ään App önt Juar as al swaar — ik hääw 49.",
  proof:"Jo san åål önt App Store.", cap1:"Faan e idee\ntu e lääsing.",
  cap2:"Naan book tu leesen.\nÄän tu följin.", ytLabel:"Luke, hü't maaget woort",
  buyLabel:"Kuupe", back:"Tubääg", soon:"Komt gau", soonSub:"Gau tu kriin.",
  stores:[ {name:"Amazon.de", fmt:["ebook"], url:""} ] },

{ id:"no", native:"Norsk", label:"Norwegian", ready:true,
  title:"49 apper. Én person.",
  sub:"Én app i året er vanskelig nok — jeg driver 49.",
  proof:"Alle er på App Store. Trykk for å se.",
  cap1:"Fra idé til lansering —\nhele veien.",
  cap2:"Ikke en bok å lese.\nEn å følge.",
  ytLabel:"Se hvordan den lages",
  buyLabel:"Kjøp", back:"Tilbake",
  soon:"Kommer snart", soonSub:"Snart tilgjengelig.",
  stores:[
    {name:"Amazon",      fmt:["ebook"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"nb", native:"Norsk Bokmål", label:"Norwegian Bokmål", ready:true,
  title:"Helt alene, 49 apper.", sub:"Én app i året er vanskelig nok — jeg driver 49.",
  proof:"Alle er på App Store.", cap1:"Fra idé til lansering —\nhele veien.",
  cap2:"Ikke en bok å lese.\nEn å følge.", ytLabel:"Se hvordan den lages",
  buyLabel:"Kjøp", back:"Tilbake", soon:"Kommer snart", soonSub:"Snart tilgjengelig.",
  stores:[ {name:"Amazon", fmt:["ebook"], url:""} ] },

{ id:"nn", native:"Nynorsk", label:"Norwegian Nynorsk", ready:true,
  title:"Heilt åleine, 49 appar.", sub:"Éin app i året er vanskeleg nok — eg driv 49.",
  proof:"Alle er på App Store.", cap1:"Frå idé til lansering —\nheile vegen.",
  cap2:"Ikkje ei bok å lese.\nEi å følgje.", ytLabel:"Sjå korleis ho blir laga",
  buyLabel:"Kjøp", back:"Tilbake", soon:"Kjem snart", soonSub:"Snart tilgjengeleg.",
  stores:[ {name:"Amazon", fmt:["ebook"], url:""} ] },

{ id:"fa", native:"فارسی", label:"Persian", ready:true, dir:"rtl",
  title:"به‌تنهایی، ۴۹ اپ.", sub:"یک اپ در سال هم سخت است — من ۴۹ تا را اداره می‌کنم.",
  proof:"همه در App Store هستند.", cap1:"از ایده تا انتشار —\nتمام مسیر.",
  cap2:"کتابی برای خواندن نیست.\nبرای دنبال‌کردن است.", ytLabel:"ببینید چگونه ساخته می‌شود",
  buyLabel:"خرید", back:"بازگشت", soon:"به‌زودی", soonSub:"به‌زودی در دسترس.",
  stores:[ {name:"Apple Books", fmt:["ebook"], url:""} ] },

{ id:"pl", native:"Polski", label:"Polish", ready:true,
  title:"49 aplikacji. Jedna osoba.",
  sub:"Jedna aplikacja rocznie to dużo — ja prowadzę 49.",
  proof:"Wszystkie są w App Store. Dotknij, by zobaczyć.",
  cap1:"Od pomysłu do premiery —\ncała droga.",
  cap2:"Nie książka do czytania.\nDo naśladowania.",
  ytLabel:"Zobacz, jak to powstaje",
  buyLabel:"Kup", back:"Wstecz",
  soon:"Wkrótce", soonSub:"Dostępne wkrótce.",
  stores:[
    {name:"Amazon.pl",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
    {name:"Legimi",      fmt:["ebook"], url:""},
  ]},

{ id:"oc", native:"Provençau", label:"Provençal", ready:true,
  title:"Soulet, 49 aplicacions.", sub:"Una aplicacion per an es ja dificila — ne gerissi 49.",
  proof:"Son totas sus l'App Store.", cap1:"De l'idèa au lançament —\ntot lo camin.",
  cap2:"Pas un libre de legir.\nUn de seguir.", ytLabel:"Agacha cossí es fach",
  buyLabel:"Crompar", back:"Tornar", soon:"Lèu", soonSub:"Disponible lèu.",
  stores:[ {name:"Amazon.fr", fmt:["ebook"], url:""} ] },

{ id:"rm", native:"Rumantsch", label:"Romansh", ready:true,
  title:"Sulet, 49 apps.", sub:"In'app l'onn è gia difficila — jau gestiunesch 49.",
  proof:"Ellas èn tuttas sin l'App Store.", cap1:"Da l'idea al lantschar —\nl'entira via.",
  cap2:"Betg in cudesch per leger.\nIn per suandar.", ytLabel:"Guarda co ch'igl vegn fatg",
  buyLabel:"Cumprar", back:"Enavos", soon:"Prest", soonSub:"Disponibel prest.",
  stores:[ {name:"Amazon.de", fmt:["ebook"], url:""} ] },

{ id:"sco", native:"Scots", label:"Scots", ready:true,
  title:"On ma lane, 49 apps.", sub:"Ae app a year is sair eneuch — A rin 49.",
  proof:"They're aw on the App Store.", cap1:"Frae idea tae launch —\nthe hale gate.",
  cap2:"No a buik tae read.\nAne tae follae.", ytLabel:"See hoo it's made",
  buyLabel:"Buy", back:"Back", soon:"Comin suin", soonSub:"Available suin.",
  stores:[ {name:"Amazon", fmt:["ebook"], url:""} ] },

{ id:"gd", native:"Gàidhlig", label:"Scottish Gaelic", ready:true,
  title:"Nam aonar, 49 aplacaid.", sub:"Tha aon aplacaid sa bhliadhna doirbh gu leòr — tha 49 agam.",
  proof:"Tha iad uile air an App Store.", cap1:"Bho bheachd\ngu foillseachadh.",
  cap2:"Chan e leabhar ri leughadh.\nFear ri leantainn.", ytLabel:"Faic mar a thèid a dhèanamh",
  buyLabel:"Ceannaich", back:"Air ais", soon:"A' tighinn a dh'aithghearr", soonSub:"Ri fhaighinn a dh'aithghearr.",
  stores:[ {name:"Amazon.co.uk", fmt:["ebook"], url:""} ] },

{ id:"sv", native:"Svenska", label:"Swedish", ready:true,
  title:"49 appar. En person.",
  sub:"En app om året är nog svårt — jag driver 49.",
  proof:"Alla finns på App Store. Tryck för att se.",
  cap1:"Från idé till lansering —\nhela vägen.",
  cap2:"Ingen bok att läsa.\nEn att följa.",
  ytLabel:"Se hur den görs",
  buyLabel:"Köp", back:"Tillbaka",
  soon:"Kommer snart", soonSub:"Snart tillgänglig.",
  stores:[
    {name:"Amazon.se",   fmt:["ebook","paper"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"ta", native:"தமிழ்", label:"Tamil", ready:true,
  title:"தனியொருவர், 49 ஆப்கள்.",
  sub:"வருடத்திற்கு ஒன்றே கடினம் — நான் 49 நடத்துகிறேன்.",
  proof:"அனைத்தும் App Store-இல் உள்ளன. பார்க்க தட்டவும்.",
  cap1:"தலைப்பு முதல் வெளியீடு வரை —\nமுழு பாதை.",
  cap2:"படிக்கும் புத்தகம் அல்ல.\nபின்பற்றும் புத்தகம்.",
  ytLabel:"எப்படி உருவாக்கப்படுகிறது என பாருங்கள்",
  buyLabel:"வாங்க", back:"பின்",
  soon:"விரைவில்", soonSub:"விரைவில் கிடைக்கும்.",
  stores:[
    {name:"Amazon.in",   fmt:["ebook"], url:""},
    {name:"Apple Books", fmt:["ebook"], url:""},
    {name:"Google Play", fmt:["ebook"], url:""},
  ]},

{ id:"tr", native:"Türkçe", label:"Turkish", ready:true,
  title:"49 uygulama. Tek kişi.",
  sub:"Yılda bir uygulama bile zor — ben 49 tane yönetiyorum.",
  proof:"Hepsi App Store'da. Görmek için dokunun.",
  cap1:"Fikirden çıkışa —\ntüm yol.",
  cap2:"Okunan değil,\ntakip edilen bir kitap.",
  ytLabel:"Nasıl yapıldığını izleyin",
  buyLabel:"Satın al", back:"Geri",
  soon:"Yakında", soonSub:"Çok yakında.",
  stores:[
    {name:"Amazon.com.tr", fmt:["ebook","paper"], url:""},
    {name:"Apple Books",   fmt:["ebook"], url:""},
    {name:"Google Play",   fmt:["ebook"], url:""},
  ]},

{ id:"uk", native:"Українська", label:"Ukrainian", ready:true,
  title:"Наодинці, 49 застосунків.", sub:"Один застосунок на рік — це важко. У мене їх 49.",
  proof:"Усі вони в App Store.", cap1:"Від ідеї до запуску —\nувесь шлях.",
  cap2:"Не книга для читання.\nКнига, якою керуються.", ytLabel:"Дивіться, як це зроблено",
  buyLabel:"Купити", back:"Назад", soon:"Незабаром", soonSub:"Скоро буде доступно.",
  stores:[ {name:"Amazon", fmt:["paper","hard"], url:""} ] },   /* paperback + hardcover only */

{ id:"cy", native:"Cymraeg", label:"Welsh", ready:true,
  title:"Ar fy mhen fy hun, 49 ap.", sub:"Mae un ap y flwyddyn yn ddigon anodd — rwy'n rhedeg 49.",
  proof:"Maen nhw i gyd ar yr App Store.", cap1:"O syniad i lansiad —\ny daith gyfan.",
  cap2:"Nid llyfr i'w ddarllen.\nUn i'w ddilyn.", ytLabel:"Gwyliwch sut mae'n cael ei wneud",
  buyLabel:"Prynu", back:"Yn ôl", soon:"Yn dod yn fuan", soonSub:"Ar gael yn fuan.",
  stores:[ {name:"Amazon.co.uk", fmt:["ebook"], url:""} ] },

{ id:"yi", native:"ייִדיש", label:"Yiddish", ready:true, dir:"rtl",
  title:"אַליין, 49 אַפּס.", sub:"איין אַפּ אַ יאָר איז שווער גענוג — איך פיר 49.",
  proof:"זיי זענען אַלע אויף App Store.", cap1:"פֿון אידעע\nביז אַרויסגעבן.",
  cap2:"נישט קיין בוך צו לייענען.\nאיינס צו נאָכפֿאָלגן.", ytLabel:"זעט ווי מע מאַכט עס",
  buyLabel:"קויפֿן", back:"צוריק", soon:"אין גיכן", soonSub:"אין גיכן פֿאַראַן.",
  stores:[ {name:"Amazon", fmt:["paper","hard"], url:""} ] },   /* paperback + LTR hardcover only */

];
